### ISSUE TITLE
showProgress=1 does not show the actual progress

### ISSUE THREAD

**Issue by jafyvilla** [BlueBrain/Fivox#12]
The progress bar finishes before the data has actually been generated. It could be because the reported progress is based on a single thread's ImageRegion (outputRegionForThread) instead of the full Image.

**Comment by eile** [comment]
Working on ZeroBuf progress display.

**Comment by eile** [comment]
Confirmed that some threads are still working when the progress observer is "done".

**Comment by eile** [comment]
itkProgressReporter:
```
      // only thread 0 should update the progress of the filter
      if ( m_ThreadId == 0 )
```
